# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_remove_gpior2_rele'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpior1',
            name='version',
            field=models.CharField(default=b'RASPBERRY 1', max_length=18),
        ),
        migrations.AddField(
            model_name='gpior2',
            name='version',
            field=models.CharField(default=b'RASPBERRY 2', max_length=18),
        ),
    ]
