# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0004_auto_20160101_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpior2',
            name='toggle_state',
        ),
        migrations.AddField(
            model_name='gpior2',
            name='status',
            field=models.CharField(choices=[(b'UNDEFINED', b'Undefined'), (b'ON', b'ON'), (b'OFF', b'OFF')], default=b'', max_length=5),
        ),
    ]
