# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0008_auto_20160317_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (19, 19), (18, 18), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27)])),
                ('sensor', models.IntegerField(choices=[(11, 11), (22, 22)])),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Lcd',
        ),
        migrations.AlterField(
            model_name='gpior1',
            name='action',
            field=models.CharField(choices=[(b'toggle light', b'toggle light')], default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='gpior2',
            name='action',
            field=models.CharField(choices=[(b'toggle light', b'toggle light')], default=b'', max_length=30),
        ),
    ]
