# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0010_auto_20160417_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemperatureSensor',
            new_name='Temperature',
        ),
    ]
