# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0012_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='text',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
