# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0019_auto_20160607_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
