# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0020_auto_20160616_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
