# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0022_auto_20160617_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(default=b'', max_length=30)),
                ('password', models.TextField()),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='temperature',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='x.MqttBroker'),
        ),
    ]
