# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0005_auto_20160109_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpior1',
            name='action',
            field=models.CharField(choices=[(b'toggle light', b'toggle light'), (b'termos', b'termos')], default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='gpior2',
            name='action',
            field=models.CharField(choices=[(b'toggle light', b'toggle light'), (b'termos', b'termos')], default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='gpior2',
            name='status',
            field=models.CharField(choices=[(b'UNDEFINED', b'Undefined'), (b'ON', b'ON'), (b'OFF', b'OFF')], default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='gpior2',
            name='text',
            field=models.CharField(default=b'type the configuration name', max_length=50),
        ),
    ]
