# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0006_auto_20160115_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lcd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_rs', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (19, 19), (18, 18), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27)], default=b'')),
                ('pin_rw', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (19, 19), (18, 18), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27)], default=b'')),
                ('pin_e', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (19, 19), (18, 18), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27)], default=b'')),
                ('pins_data', models.IntegerField(validators=[21, 22, 23, 24])),
                ('cols', models.IntegerField(default=20)),
                ('rows', models.IntegerField(default=4)),
                ('dotsize', models.IntegerField(default=8)),
            ],
        ),
        migrations.AlterField(
            model_name='gpior1',
            name='text',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
