# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0007_auto_20160317_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpior2',
            name='text',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
