# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0014_gpior2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='id_icon',
            field=models.CharField(default=b'', max_length=3),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(upload_to=b'media_foto'),
        ),
    ]
