# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0015_auto_20160428_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpior2',
            old_name='text',
            new_name='item',
        ),
        migrations.AddField(
            model_name='gpior2',
            name='room',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='icon',
            name='id_icon',
            field=models.CharField(default=b'', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='text',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
