# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0016_auto_20160428_1936'),
        ('x', '0015_auto_20160427_0759'),
    ]

    operations = [
    ]
