# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0023_auto_20160617_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='room',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
